Task/sdet 208 date selector component
ZeroGachis/smartway-react-native-ui pull request #151
Opened 2023-12-18 14:59 UTC by AdrienCasta

2023-12-18 15:04 UTC, JosselinTILLAY commented on Storybook/components/DateSelector/DateField.stories.tsx
> +export const Default = (args: ComponentPropsWithRef<typeof DateField>) => {
Pourquoi utiliser ComponentPropsWithRef? Il me semblait que c'était plutôt utiliser quand on avait pas accès à l'interface des props d'un composant. Quand on a accès à l'interface, c'est plus simple de l'utiliser non ?

2023-12-18 15:06 UTC, AdrienCasta commented on Storybook/components/DateSelector/DateField.stories.tsx
> +export const Default = (args: ComponentPropsWithRef<typeof DateField>) => {
J'ai pas trouver meilleur façon d'accéder au `ref `avec cette manière, tu ferais comment sinon ?

2023-12-19 10:08 UTC, tuxtoby commented on src/components/dateSelector/DateField.tsx
> +import React, { ComponentPropsWithRef, forwardRef, useState } from 'react';
Le prochain coup, penser à split le rename et le diff dans 2 commits, c'est compliqué pour savoir ce qui a vraiment changé ^^

2023-12-19 10:45 UTC, AudBrou requested changes

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateField.tsx
> +import React, { ComponentPropsWithRef, forwardRef, useState } from 'react';
Pourquoi un tel diff ?

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateSelector.tsx
> +                keyboardType='number-pad'
Pourquoi le datefield a un keyboard type ? Il devrait porter son keyboard numérique tout seul, il n'y a aucune raison d'avoir un autre type de clavier sur un DateField

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateSelector.tsx
> +                inputMode='numeric'
Idem, quel est cet inputMode ?

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateSelector.tsx
> +                selectTextOnFocus={true}
Je ne comprends pas pourquoi on remet toutes ces props dans chaque champ ici. Ca nuit grandement à la lisibilité du code, et étant donné que le dateField est fait spécifiquement pour ce champ dateSelector (qui plus est non exposé), il devrait déjà porter toutes ces valeurs par défaut.

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateSelector.tsx
> +const useDateRef = () => {
Je ne suis pas très familière des ref, en lisant seulement ce bout de code j'ai vraiment du mal à comprendre ce qu'il fait.

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateSelector.tsx
> +        return value.length === 2;
Tu utilises aussi cette valeur pour le padding, je l'extrairait en constante pour la réutiliser ici.

2023-12-19 10:45 UTC, AudBrou commented on src/components/dateSelector/DateSelector.tsx
> +const field = initField();
J'ai du mal à saisir le rôle/intérêt de ce champ field tout seul ici. C'est pour éviter certains reload ?

2023-12-19 18:15 UTC, AdrienCasta commented on src/components/dateSelector/DateField.tsx
> +import React, { ComponentPropsWithRef, forwardRef, useState } from 'react';
my bad !

2023-12-19 18:16 UTC, AdrienCasta commented on src/components/dateSelector/DateField.tsx
> +import React, { ComponentPropsWithRef, forwardRef, useState } from 'react';
c'est un rename de fichier qui a mis le bazar, my bad !

2023-12-19 18:19 UTC, AdrienCasta commented on src/components/dateSelector/DateSelector.tsx
> +                keyboardType='number-pad'
oh oui ça n'a pas de sens ! je bossais avec un simple `TextInput` avant d'intégrer le `DateField`, beaucoup de props sont donc caduques

2023-12-19 18:23 UTC, AdrienCasta commented on src/components/dateSelector/DateSelector.tsx
> +                keyboardType='number-pad'
c'est corrigé 6f3d741864a8b8b919d610cf5d075cff5c211111

2023-12-19 18:24 UTC, AdrienCasta commented on src/components/dateSelector/DateSelector.tsx
> +                inputMode='numeric'
corrigé ! 6f3d741864a8b8b919d610cf5d075cff5c211111

2023-12-19 18:32 UTC, AdrienCasta commented on src/components/dateSelector/DateSelector.tsx
> +const useDateRef = () => {
L'idée est de pouvoir `focus` ou `blur` des `DateField`. React Native nous permet de le faire en passant par des `refs`.
J'ai donc créer mes refs et mes comportement focus/blur puis je les ai isolé dans un hook spécifique pour ne pas polluer l'implémentation du `DateSelector`. Le nom est peut être maladroit, on peut peut-être l'améliorer ?

2023-12-19 18:35 UTC, AdrienCasta commented on src/components/dateSelector/DateSelector.tsx
> +        return value.length === 2;
Corrigé ! f45f47b68598ff64b5579280ea6de68fe55cb749

2023-12-19 18:42 UTC, AdrienCasta commented on src/components/dateSelector/DateSelector.tsx
> +const field = initField();
Oui, je voulais isoler ma logique de validation des différents `DateField`. Etant donné que cette logique de dépend pas du cycle de vie du composant (pas de state), j'ai pris la décision de l'instancier à l'extérieur du composant, évitant ainsi la réinstanciation à chaque mise à jour du state. A noter que j'aurais pu le mettre dans un `useCallback`  mais cela aurait rajouté une couche de complexité à la lecture

2023-12-21 08:13 UTC, closed without merging

2023-12-21 14:21 UTC, JosselinTILLAY commented
A tester : est-ce que le initField est bien scopé à une instance du DateSelector ? Si j'ai deux DateSelector sur la page, est-ce qu'ils partagent le même `field` ?