:sparkles: GDS-18 - add smartway design token
ZeroGachis/smartway-react-native-ui pull request #192
Opened 2024-02-16 11:00 UTC by ulricden

2024-02-16 13:47 UTC, clementdejoie requested changes
Il va falloir revoir notre proposition. Les ThemeProvider ne semblent pas fait pour être imbriqués

2024-02-16 14:23 UTC, ulricden commented
Je suis tout a fais d'accord c'est pour ça qu'il va falloir faire le tour de toute 'e désigne pour les remplacer

2024-02-16 15:07 UTC, clementdejoie commented
C'est une solution

2024-03-19 14:45 UTC, clementdejoie approved these changes

2024-03-20 10:39 UTC, AdrienCasta approved these changes

2024-03-20 19:51 UTC, merged